---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-dns
  namespace: traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-dns
  namespace: traefik
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-dns
  namespace: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-dns
subjects:
- kind: ServiceAccount
  name: traefik-dns
  namespace: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-dns
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-dns
  template:
    metadata:
      labels:
        app: traefik-dns
    spec:
      serviceAccountName: traefik-dns
      containers:
      - name: traefik-dns
        image: nicholasdille/traefik-dns:latest
        imagePullPolicy: Always
        args:
        - --namespace
        - traefik
        - --selector
        - app=traefik
        - --dnsendpoint
        - traefik-dns
