---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-dns
  namespace: traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-dns
  namespace: traefik
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-dns
  namespace: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-dns
subjects:
- kind: ServiceAccount
  name: traefik-dns
  namespace: traefik
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-dns
  namespace: traefol
spec:
  serviceAccountName: traefik-dns
  replicas: 1
  selector:
    matchLabels:
      app: traefik-dns
  template:
    metadata:
      labels:
        app: traefik-dns
    spec:
      containers:
      - name: traefik-dns
        image: nicholasdille/traefik-dns
        args:
        - --namespace=traefik
        - --selector=service=app
        - --dnsendpoint=traefik-dns
