---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-dns
  namespace: traefik
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints
  verbs:
  - "*"
