---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-dns
  namespace: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: traefik-dns
subjects:
- kind: ServiceAccount
  name: traefik-dns
  namespace: traefik
