name: docker-build2

on:
  push:
    branches:
    - master
    paths:
    - "shell-operator/**"
  schedule:
  - cron:  '0 7 * * *'

jobs:
  build:
    name: docker-build2
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: shell-operator
        cache-from: nicholasdille/traefik-dns:shell-operator
        #push: true
        tags: nicholasdille/traefik-dns:shell-operator

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: nicholasdille/traefik-dns:shell-operator
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: shell-operator
        cache-from: nicholasdille/traefik-dns:shell-operator
        push: true
        tags: nicholasdille/traefik-dns:shell-operator
